### ISSUE TITLE
Display a better error message when Docker Desktop is not running

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-local-server#268]
When running `composer server` for the first time on a project and Docker Desktop is not running, there's a rather cryptic error. It would be great if the command first checked to see if Docker is running, and display a user friendly message if not.

The error shown is:

```
> composer server
Starting...
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 259, in _raise_for_status
  File "site-packages/requests/models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 205, in _retrieve_server_version
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/api/client.py", line 265, in _result
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'dial unix docker.raw.sock: connect: connection refused'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "site-packages/docker/api/client.py", line 188, in __init__
  File "site-packages/docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error ("b'dial unix docker.raw.sock: connect: connection refused'")
[30221] Failed to execute script docker-compose
Could not start traefik proxy.
```

**Comment by ferschubert-hm** [comment]
Tests with v22 - for an existing env: 

```
➜  local-srv-fix composer server start
Starting...
unable to get image 'traefik:1.7': Cannot connect to the Docker daemon at unix:///Users/fsck/.docker/run/docker.sock. Is the docker daemon running?
Could not start traefik proxy.
➜  local-srv-fix composer server      
Starting...
unable to get image 'traefik:1.7': Cannot connect to the Docker daemon at unix:///Users/fsck/.docker/run/docker.sock. Is the docker daemon running?
```

**Comment by vladislavhmn** [comment]
Cannot reproduce, new error stack looks informative and user-friendly enough:

```sh
vladislavdenishev@Vladislavs-MacBook-Pro ~ % composer create-project altis/skeleton altis-local-test

[output truncated, no errors, two deprecation notices]

vladislavdenishev@Vladislavs-MacBook-Pro ~ % cd altis-local-test
vladislavdenishev@Vladislavs-MacBook-Pro altis-local-test % composer server start

[output truncated, up until the error concerning Docker desktop not running]

Generated SSL certificate successfully.
Cannot connect to the Docker daemon at unix:///Users/vladislavdenishev/.docker/run/docker.sock. Is the docker daemon running?
unable to get image 'traefik:1.7': Cannot connect to the Docker daemon at unix:///Users/vladislavdenishev/.docker/run/docker.sock. Is the docker daemon running?
Could not start traefik proxy.
```

Closing.
